fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin
    
_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin
    
ahmed_admin:
    resource: "@AhmedAdminBundle/Controller/"
    type:     annotation
    prefix:   /

ahmed_user:
    resource: "@AhmedUserBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
