services:
#    ahmed_user.example:
#        class: Ahmed\UserBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    ahmed_user.admin.user:
        class: Ahmed\UserBundle\Admin\UserAdmin
        arguments: [~, Ahmed\UserBundle\Entity\User, AhmedUserBundle:UserAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: User }
